const NATIONALITY_TO_FLAG_CODE: Record<string, string> = {
  argentina: 'ar',
  austrian: 'at',
  austria: 'at',
  australian: 'au',
  australia: 'au',
  american: 'us',
  'united states': 'us',
  usa: 'us',
  belgian: 'be',
  belgium: 'be',
  brazil: 'br',
  brazilian: 'br',
  canada: 'ca',
  canadian: 'ca',
  chinese: 'cn',
  china: 'cn',
  danish: 'dk',
  denmark: 'dk',
  estonia: 'ee',
  estonian: 'ee',
  finland: 'fi',
  finnish: 'fi',
  france: 'fr',
  french: 'fr',
  germany: 'de',
  german: 'de',
  'great britain': 'gb',
  british: 'gb',
  'united kingdom': 'gb',
  england: 'gb',
  italy: 'it',
  italian: 'it',
  mexico: 'mx',
  mexican: 'mx',
  monaco: 'mc',
  monegasque: 'mc',
  netherlands: 'nl',
  dutch: 'nl',
  'south africa': 'za',
  'south african': 'za',
  'new zealand': 'nz',
  'new zealander': 'nz',
  sweden: 'se',
  swedish: 'se',
  switzerland: 'ch',
  swiss: 'ch',
  spain: 'es',
  spanish: 'es',
  thailand: 'th',
  thai: 'th',
  japan: 'jp',
  japanese: 'jp',
  hungary: 'hu',
  hungarian: 'hu',
};

export function getFlagCodeFromNationality(nationality: string): string | null {
  const normalized = nationality.trim().toLowerCase();
  return NATIONALITY_TO_FLAG_CODE[normalized] ?? null;
}
